<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name ="NationalParks"> <!-- Root element-->
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NationalPark" maxOccurs="unbounded"><!-- Park elements-->
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type ="xs:string"/> <!-- Park Name element-->
							<xs:element name="Phone" type="xs:string" maxOccurs="unbounded"/> <!-- Park Phone Number element-->
							<xs:element name="Address"> <!-- Park Address element-->
								<xs:complexType>
									<xs:sequence>
										<xs:element name ="Number" type="xs:string"/> <!-- Adress building number element-->
										<xs:element name ="Street" type="xs:string"/> <!-- Address street name element-->
										<xs:element name ="City" type="xs:string"/> <!-- Address City name element-->
										<xs:element name ="State" type="xs:string"/> <!-- Address state name element-->
										<xs:element name ="Zip" type="xs:string"/> <!-- Address zipcode element-->
									</xs:sequence>
									<xs:attribute name ="NearestAirport" type="xs:string" use ="required"/> <!-- Required attribute of nearest airport to address-->
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Rating" type="xs:string" use="optional"/> <!-- Optional attribute of rating of park-->
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		
		
		
	</xs:element>
	
	
	
	
</xs:schema>